#!/bin/bash
# Validate project readiness for agent initialization

set -e

echo "========================================="
echo "PROJECT VALIDATION"
echo "========================================="
echo ""

VALIDATION_FAILED=0

# Check if we're in a project directory (not the template)
if [ ! -d "memory-bank" ]; then
  echo "ERROR: memory-bank/ directory not found"
  echo "       Are you in a project created from the template?"
  echo "       Run: ../ai-project-template/scripts/setup-project.sh <project-name>"
  exit 1
fi

echo "Checking project setup..."
echo ""

# Check Memory Bank files exist (but don't require customization yet)
echo "[1/3] Validating Memory Bank files..."

MEMORY_BANK_FILES=(
  "projectBrief.md"
  "productContext.md"
  "activeContext.md"
  "systemPatterns.md"
  "techContext.md"
  "progress.md"
)

for file in "${MEMORY_BANK_FILES[@]}"; do
  if [ ! -f "memory-bank/$file" ]; then
    echo "  ERROR: memory-bank/$file does not exist"
    echo "         Run setup-project.sh first"
    VALIDATION_FAILED=1
  elif [ -f "memory-bank/$file.template" ]; then
    echo "  WARNING: memory-bank/$file.template still exists"
    echo "           Setup script should have renamed this"
  fi
done

if [ $VALIDATION_FAILED -eq 0 ]; then
  echo "  ✓ All Memory Bank files exist"
  echo "    (Will be updated by Claude during initialization)"
fi

# Check PRD exists
echo ""
echo "[2/3] Validating PRD..."

if [ ! -f "_docs/prd.md" ]; then
  echo "  ERROR: _docs/prd.md does not exist"
  echo "         Create your PRD before using project-prompt-template.md"
  echo ""
  echo "         Your PRD should include:"
  echo "         - Product vision and goals"
  echo "         - User stories and features"
  echo "         - Technical requirements"
  echo "         - Platform and performance requirements"
  echo "         - Security and scalability considerations"
  VALIDATION_FAILED=1
else
  # Check PRD has substantial content (more than template boilerplate)
  PRD_LINES=$(wc -l < "_docs/prd.md")
  if [ "$PRD_LINES" -lt 20 ]; then
    echo "  WARNING: _docs/prd.md seems short ($PRD_LINES lines)"
    echo "           Ensure it contains complete requirements"
  else
    echo "  ✓ PRD exists with $PRD_LINES lines"
  fi
fi

# Check documentation files that should NOT exist yet
echo ""
echo "[3/3] Verifying pre-initialization state..."

SHOULD_NOT_EXIST=(
  "_docs/architecture.md"
  "_docs/task-list.md"
  "_docs/task-tracker.md"
  "_docs/best-practices.md"
)

for file in "${SHOULD_NOT_EXIST[@]}"; do
  if [ -f "$file" ]; then
    echo "  INFO: $file already exists"
    echo "        This should be generated by Claude during initialization"
    echo "        If re-initializing, consider backing up existing file"
  fi
done

echo ""
echo "========================================="

if [ $VALIDATION_FAILED -eq 0 ]; then
  echo "✓ PROJECT VALIDATION PASSED"
  echo "========================================="
  echo ""
  echo "Your project is ready for agent initialization."
  echo ""
  echo "Next steps:"
  echo "1. Open Cursor or Claude Code"
  echo "2. Use this prompt:"
  echo "   @_docs/_boilerplate/project-prompt-template.md"
  echo "3. Claude will generate:"
  echo "   - _docs/architecture.md"
  echo "   - _docs/task-list.md"
  echo "   - _docs/task-tracker.md"
  echo "   - _docs/best-practices.md"
  echo ""
else
  echo "✗ PROJECT VALIDATION FAILED"
  echo "========================================="
  echo ""
  echo "Fix the errors above before proceeding."
  echo ""
  exit 1
fi
